name : Fitxers

on:
  push:
    branches: [ main ]

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Comprovació del Codi
        uses: actions/checkout@v5
        
      - name: Executa script nova línia
        run: bash scripts/novalinia.sh
